[package]
name = "api"
version = "0.1.0"
authors = ["GONZALO MATEOS GLEZ-SICILIA <gonzalomateosglezsicilia@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0" features = ["postgres"] }
dotenv = "0.9.0"
